CREATE TABLE tasks (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    author_id BIGINT NOT NULL,
    author_name VARCHAR(20) NOT NULL,
    title VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    createTime DATETIME DEFAULT CURRENT_TIMESTAMP,
    editTime DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE author (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    author_name VARCHAR(20) NOT NULL,
    email VARCHAR(40) NOT NULL,
    joinTime DATETIME DEFAULT CURRENT_TIMESTAMP,
    editTime DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)
